dist: trusty

before_install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl

jobs:
  include:
  - stage: redeploy cluster
    script:
    - cd k8s
    - sed -i -e 's|KUBE_CA_CERT|'"${KUBE_CA_CERT}"'|g' kubeconfig
    - sed -i -e 's|KUBE_ENDPOINT|'"${KUBE_ENDPOINT}"'|g' kubeconfig
    - sed -i -e 's|KUBE_ADMIN_CERT|'"${KUBE_ADMIN_CERT}"'|g' kubeconfig
    - sed -i -e 's|KUBE_ADMIN_KEY|'"${KUBE_ADMIN_KEY}"'|g' kubeconfig
    - sed -i -e 's|KUBE_USERNAME|'"${KUBE_USERNAME}"'|g' kubeconfig
    - export KUBECONFIG=./kubeconfig
    - echo "travis commit message ${TRAVIS_COMMIT_MESSAGE}"
    - kubectl get pods
    - echo "kubectl set image deployment backend-feed backend-feed=homac/udacity-restapi-feed:${TRAVIS_COMMIT_MESSAGE}"
    - kubectl set image deployment backend-feed backend-feed=homac/udacity-restapi-feed:${TRAVIS_COMMIT_MESSAGE}
    - kubectl set image deployment backend-user backend-user=homac/udacity-restapi-user:${TRAVIS_COMMIT_MESSAGE}
    - kubectl set image deployment frontend frontend=homac/udacity-frontend:${TRAVIS_COMMIT_MESSAGE}
    - kubectl set image deployment reverseproxy reverseproxy=homac/reverseproxy:${TRAVIS_COMMIT_MESSAGE}
    - kubectl get pods
